export const colors = {
  whiteColor:'#fff',
  smokeWhiteColor: '#F5F5F5',
  blackColor: '#000',
  lightBlackColor: '#999999',
  greenColor: '#11C58F',
  greyColor: '#ABABAB',
  darkGreenColor: '#03987D',
  gradientGreenColor: 'rgba(17, 197, 143, 0.3)',
  lightGreyColor: '#F1F1F1',
  offWhiteColor: '#F4F4F4',
  inputBorderColor: '#E8E8E8',
  innerBorderColor: '#E1E1E1',
  cardBorderColor: '#CCCCCC',
  lightBlueColor: '#6086F0',
  gradientBlueColor: 'rgba(96, 134, 240, 0.3)',
  orangeColor: '#FFB075',
  // lightOrangeColor: '#FBDBC3',
  pearlColor: '#37B3CB',
  lightRedColor: '#CB3769',
  lightOrangeColor: '#F5924C',
  lightGreenColor: '#2E9C96',
  actvityGreenColor: '#37CB99',
  printingColor: '#5DA7CE',
};

export const fonts = {
  avenir_bold:'AvenirLTStd-Black',
  avenir_regular:'AvenirLTStd-Book',
  avenir_light:'AvenirLTStd-Roman',
  avenir_next: 'AvenirNextLTPro-Heavy',
}
